services:
  pi-proxy:
    image: docker.io/ubuntu/squid:latest
    container_name: pi-proxy
    volumes:
      - ./proxy/squid.conf:/etc/squid/squid.conf:ro
      - ./proxy/allowlist.txt:/etc/squid/allowlist.txt:ro
      - squid-cache:/var/spool/squid
      - squid-logs:/var/log/squid
    cap_add:
      - NET_RAW
    ports:
      - "3128:3128"
    networks:
      - pi-internal-net
      - pi-external-net

  pi-agent:
    image: ghcr.io/vishal929/pi-sandbox:latest
    container_name: pi-agent
    pull_policy: newer
    volumes:
      - pi-volume:/home/node/.pi/agent/
${DYNAMIC_VOLUMES}
    environment:
      - http_proxy=http://pi-proxy:3128
      - https_proxy=http://pi-proxy:3128
      - no_proxy=localhost,127.0.0.1
    depends_on:
      - pi-proxy
    stdin_open: true
    tty: true
    networks:
      - pi-internal-net
    env_file:
      - ./credentials/credentials.env
networks:
  pi-internal-net:
    internal: true
  pi-external-net:

volumes:
  pi-volume:
  squid-cache:
  squid-logs:
