# Define the allowlist file path inside the proxy container
acl allowed_domains dstdomain "/etc/squid/allowlist.txt"
acl SSL_ports port 443

# Only allow https requests from allowlist and block everything else
http_access allow allowed_domains
http_access deny all
http_access deny !SSL_ports

# Default Squid port
http_port 3128
